name: Polaris Security Scan
on:
  push:
    branches:
      - main
      - master
      - develop
      - stage
      - release
  pull_request:
    branches:
      - main
      - master
      - develop
      - stage
      - release
  workflow_dispatch: {}
jobs:
  polaris:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

        # Step 2: Set up Java
      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 23
          architecture: x64
          cache: 'maven'

      # Step 3: Install Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      # Step 4: Install Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      # Step 5: Install Java dependencies
      - name: Install Maven dependencies
        run: mvn --no-transfer-progress clean install -DskipTests

      # Step 6: Install Node.js dependencies
      - name: Install npm dependencies
        run: npm install

      # Step 7: Build the project
      - name: Build with Maven
        run: mvn --no-transfer-progress verify
        
      - name: Polaris Security Scan
        id: polaris-scan
        uses: blackduck-inc/black-duck-security-scan@v2
        with:
          polaris_server_url: ${{ vars.POLARIS_URL }}
          polaris_access_token: ${{ secrets.POLARIS_ACCESS_TOKEN }}
          polaris_assessment_types: SCA
          polaris_waitForScan: true
          mark_build_status: failure
          include_diagnostics: false
          polaris_prComment_enabled: false
          polaris_reports_sarif_create: false
          polaris_upload_sarif_report: false
